version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass